navigation:
  # =========================
  # GPIO PINS
  # =========================
  pin_left: 18  # PIN 12
  pin_right: 13 # PIN 33
  pin_spray: 12 # PIN 32

  # =========================
  # ESC PWM SETTINGS (µs)
  # =========================
  pwm_stop: 1500
  pwm_max_fwd: 2000
  pwm_max_bwd: 1000

  motor_frequency: 10000
  wheel_base: 0.445

  # =========================
  # DRIVE LIMITS
  # =========================
  max_linear: 0.15      # m/s
  max_angular: 0.4     # rad/s

  # =========================
  # SAFETY / TIMING
  # =========================
  cmd_timeout: 0.5
  forward_velocity:  0.1    # m/s – Normalgeschwindigkeit vorwärts
  angular_velocity:  0.5    # rad/s – Drehgeschwindigkeit

  distance_tolerance: 1.5   # m – Waypoint gilt als erreicht
  angle_tolerance:   45.0   # Grad – ab wann dreht der Roboter

    # ── GPS-Qualität ───────────────────────────────────────────────────────
    # -1 = jeder Fix reicht  |  0 = normaler GPS-Fix  |  1 = nur RTK
  min_gps_status: 0

  waypoints:
    - [50.04414233333333, 10.208408566666666]
    #- [50.04359431666666, 10.207527716666666]
    #- [50.04414, 10.20848]
    #- [50.04353, 10.20770]
    

