diff_drive_controller:
  type: diff_drive_controller/diff_drive_controller
  left_wheel: 'left_wheel_joint'
  right_weel: 'right_wheel_joint'
  wheel_separation: 0.3
  wheel_radius: 0.05
  publish_rate: 1000.0
  cmd_vel_timeout: 0.5