motor_driver:
  # =========================
  # GPIO PINS
  # =========================
  pin_right: 18  # PIN 12
  pin_right_reverse: 27
  right_motor_reversed: true
  pin_left: 13 # PIN 33
  pin_left_reverse: 17
  left_motor_reversed: false
  pin_spray: 12 # PIN 32

  encoder_right_a: 26
  encoder_right_b: 6
  encoder_right_c: 5
  encoder_left_a: 16
  encoder_left_b: 23
  encoder_left_c: 24
  encoder_pull_up: false
  encoder_publish_rate: 5.0

  # =========================
  # ESC PWM SETTINGS (µs)
  # =========================
  pwm_stop: 1500
  pwm_max_fwd: 2000
  pwm_max_bwd: 1000

  motor_frequency: 10000
  wheel_base: 0.445

  # =========================
  # DRIVE LIMITS
  # =========================
  max_linear: 0.5      # m/s
  max_angular: 0.4     # rad/s

  # =========================
  # SAFETY / TIMING
  # =========================
  cmd_timeout: 0.5 
